name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup chrome driver
      uses: browser-actions/setup-chrome@v1
      id: setup-chrome
      with:
        chrome-version: 135
        install-chromedriver: true
        install-dependencies: true
        
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Run tests
      run: mvn clean test -Dheadless=true
